---
# Cluster storage options.
storage_type: filesystem  # options: 'filesystem', 'zfs'
storage_zfs_pool_name: zfsdata
#storage_nfs_dir: '{{ storage_zfs_pool_name }}'  # Use this for 'zfs'
storage_nfs_dir: "srv"  # Use this for 'filesystem'
storage_nfs_share_name: nfsshare

# These networking variables are only necessary if using optional static and
# remote networking features in the `tasks/networking` playbooks.
ipv4_subnet_prefix: "10.1.1"
ipv4_gateway: "10.1.1.1"
dns4_servers: "{{ ipv4_gateway }}"
active_internet_interface: "wlan0"
reverse_tunnel_enable: false
reverse_tunnel_vps_username: my-vps-username
reverse_tunnel_vps_hostname: my-vps-hostname
control_plane_router_setup: false
